changes

diff --git a/bin/upgrade b/bin/upgrade
--- a/bin/upgrade
+++ b/bin/upgrade
@@ -36,32 +36,36 @@ case $1 in
         ;;
 esac
 
+echo '┌────────────────────────────────────────────────────────────────────────────┐'
+echo '│ >>> upgrade .config/projects                                               │'
+echo '└────────────────────────────────────────────────────────────────────────────┘'
+
 ### Kadena projects
 
-echo ~/kadena/pact-fv
-(
-    cd ~/kadena/pact-fv
-    source .envrc
-    cabal v2-update
-    cabal v2-configure --enable-tests --disable-profiling --disable-executable-profiling
-    cabal v2-build
-    cabal v2-test
-) > /tmp/pact-fv-build.log 2>&1
+# echo ~/kadena/pact-fv
+# (
+#     cd ~/kadena/pact-fv
+#     source .envrc
+#     cabal v2-update
+#     cabal v2-configure --enable-tests --disable-profiling --disable-executable-profiling
+#     cabal v2-build
+#     cabal v2-test
+# ) > /tmp/pact-fv-build.log 2>&1
 
-if [[ $? = 0 ]]; then echo done; else echo FAIL; fi
+# if [[ $? = 0 ]]; then echo done; else echo FAIL; fi
 
-echo ~/kadena/evm/reth
-(
-    cd ~/kadena/evm/reth
-    source .envrc
-    cargo update
-    cargo build
-    cargo test
-    cargo doc
-    cargo clippy
-) > /tmp/reth-build.log 2>&1
+# echo ~/kadena/evm/reth
+# (
+#     cd ~/kadena/evm/reth
+#     source .envrc
+#     cargo update
+#     cargo build
+#     cargo test
+#     cargo doc
+#     cargo clippy
+# ) > /tmp/reth-build.log 2>&1
 
-if [[ $? = 0 ]]; then echo done; else echo FAIL; fi
+# if [[ $? = 0 ]]; then echo done; else echo FAIL; fi
 
 ### Coq projects
 
